### ISSUE TITLE
登録内容が信頼できる情報源に基づいているか判別できるようにして欲しい

### ISSUE THREAD

**Issue by ymoto** [igapyon/cityinfojp#30]
情報の信頼性を担保するために、都道府県や市区町村が情報源である登録を判別できるようにして欲しい。

例えば、

- リンク先の情報源が、都道府県や市区町村など１次ソースからの発表であること
  - 報道機関によるニュースなどの２次ソースではないこと
- cityinofjpへの登録内容が妥当であることを、第三者がリンク先と比較して検証済みであること

を満たした登録を「１次ソース確認済み」として識別できるようにする、といった方法が考えられる。

**Comment by igapyon** [comment]
「公式」サイトかどうかをバッジとして表示するような機能追加をします。

**Comment by igapyon** [comment]
URLをもとに一次ソースかどうか判定して、一次ソースであればアイコンを表示するロジックを実装しました。
